image:
  file: .gitpod.Dockerfile

tasks:
  - before: cd /workspace/tfjs-mobile-app-tutorial/my-tfjs-app
    init: yarn
    command: yarn start
    
ports:
  - port: 3000-19003
    onOpen: ignore
  - port: 19004-19010
    onOpen: open-browser